### ISSUE TITLE
Declare task dependencies like rake

### ISSUE THREAD

**Issue by psparrow** [ianks/attr-gather#7]
What do you think of declaring task dependencies similar to how rake does it?

old:
```ruby
task :fetch_user do |t|
  t.depends_on = [:fetch_post]
end
```

new: 
```ruby
task fetch_user: :fetch_post
```

**Comment by ianks** [comment]
Not exactly like rake, but tasks can be configured in one line like so:

```ruby
task :fetch_user, depends_on: [:fetch_post]
```

I think i'll close this issue for now unless someone feels strongly about this?
